export const settings = {
	alerts: {},
	days: ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
	language: 'en',
	lookups: {
		en: {
			days: {
				monday: 'Monday',
				tuesday: 'Tuesday',
				wednesday: 'Wednesday',
				thursday: 'Thursday',
				friday: 'Friday',
				saturday: 'Saturday',
				sunday: 'Sunday',
			},
			types: {
				'11': '11th Step Meditation',
				'12x12': '12 Steps & 12 Traditions,',
				ASBI: 'As Bill Sees It',
				BA: 'Babysitting Available',
				B: 'Big Book',
				H: 'Birthday',
				BRK: 'Breakfast',
				AN: 'Candlelight',
				CF: 'Child-Friendly',
				C: 'Closed',
				'AL-AN': 'Concurrent with Al-Anon',
				AL: 'Concurrent with Alateen',
				XT: 'Cross Talk Permitted',
				DR: 'Daily Reflections',
				DB: 'Digital Basket',
				D: 'Discussion',
				DD: 'Dual Diagnosis',
				EN: 'English',
				FF: 'Fragrance Free',
				FR: 'French',
				G: 'Gay',
				GR: 'Grapevine',
				NDG: 'Indigenous',
				ITA: 'Italian',
				JA: 'Japanese',
				KOR: 'Korean',
				L: 'Lesbian',
				LIT: 'Literature',
				LS: 'Living Sober',
				LGBTQ: 'LGBTQ',
				MED: 'Meditation',
				M: 'Men',
				N: 'Native American',
				BE: 'Newcomer',
				NS: 'Non-Smoking',
				O: 'Open',
				POC: 'People of Color',
				POL: 'Polish',
				POR: 'Portuguese',
				P: 'Professionals',
				PUN: 'Punjabi',
				RUS: 'Russian',
				A: 'Secular',
				ASL: 'Sign Language',
				SM: 'Smoking Permitted',
				S: 'Spanish',
				SP: 'Speaker',
				ST: 'Step Meeting',
				TR: 'Tradition Study',
				T: 'Transgender',
				X: 'Wheelchair Access',
				XB: 'Wheelchair-Accessible Bathroom',
				W: 'Women',
				Y: 'Young People',
			},
		},
	},
	print_settings: {
		preferred_source: {
			name: 'bg_name',
			notes: 'bg_notes',
		},
	},
	print_strings: {
		en: {
			am: 'AM',
			friday: 'Friday',
			midnight: 'Mid',
			monday: 'Monday',
			noon: 'Noon',
			pm : 'PM',
			saturday: 'Saturday',
			sunday: 'Sunday',
			thursday: 'Thursday',
			tuesday: 'Tuesday',
			types_codes: {
				'11': '11',
				'12x12': '12',
				ABSI: 'ABSI',
				BA: 'BA',
				B: 'B',
				H: 'H',
				BRK: 'BRK',
				AN: 'AN',
				CF: 'CF',
				C: 'C',
				'AL-AN': 'AL-AN',
				AL: 'AL',
				XT: 'XT',
				DR: 'DR',
				DB: 'DB',
				D: 'D',
				DD: 'DD',
				EN: 'EN',
				FF: 'FF',
				FR: 'FR',
				G: 'G',
				GR: 'GR',
				NDG: 'NDG',
				ITA: 'ITA',
				JA: 'JA',
				KOR: 'KOR',
				L: 'L',
				LIT: 'LIT',
				LS: 'LS',
				LGBTQ: 'LGBTQ',
				MED: 'MED',
				M: 'M',
				N: 'N',
				BE: 'BE',
				NS: 'NS',
				O: 'O',
				POC: 'POC',
				POL: 'POL',
				POR: 'POR',
				P: 'P',
				PUN: 'PUN',
				RUS: 'RUS',
				A: 'A',
				ASL: 'ASL',
				SM: 'SM',
				S: 'S',
				SP: 'SP',
				ST: 'ST',
				TR: 'TR',
				T: 'T',
				X: 'X',
				XB: 'XB',
				W: 'W',
				Y: 'Y',
			},
			wednesday: 'Wednesday',
		},
	},
}

export default settings;